# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simple_audit}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabriel Tarnovan"]
  s.date = %q{2010-06-07}
  s.email = %q{gabriel.tarnovan@cubus.ro}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "TODO"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO",
     "lib/app/helpers/simple_audit_helper.rb",
     "lib/app/models/audit.rb",
     "lib/simple_audit.rb",
     "rails/init.rb",
     "screenshot.png",
     "simple_audit.gemspec",
     "tasks/simple_audit_tasks.rake",
     "test/simple_audit_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/gtarnovan/simple_audit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{simple_audit}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple auditing solution for ActiveRecord models}
  s.test_files = [
    "test/test_helper.rb",
     "test/simple_audit_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

